In [2]:
import numpy as np

In [28]:
# operações entre arrays

array1 = np.array([[1, 1], [2, 2]])
array2 = np.array([[1, 2], [3, 4]])

print('soma:\n', array1 + array2)
print('subtração:\n', array1 - array2)
print('multiplicação:\n', array1 * array2)
print('divisão:\n', array1 / array2)
print('exponencial:\n', array1 ** array2)
print('multiplicação entre matrizes:\n', array1 @ array2)

soma:
 [[2 3]
 [5 6]]
subtração:
 [[ 0 -1]
 [-1 -2]]
multiplicação:
 [[1 2]
 [6 8]]
divisão:
 [[1.         0.5       ]
 [0.66666667 0.5       ]]
exponencial:
 [[ 1  1]
 [ 8 16]]
multiplicação entre matrizes:
 [[ 4  6]
 [ 8 12]]


In [24]:
# operações entre arrays

array1 = np.array([[1, 1], [2, 2]])
array2 = np.array([[1, 2], [3, 4]])

print('soma:\n', np.add(array1, array2))
print('subtração:\n', np.subtract(array1, array2))
print('multiplicação:\n', np.multiply(array1,array2))
print('divisão:\n', np.divide(array1, array2))
print('exponencial:\n', np.power(array1, array2))
print('multiplicação entre matrizes:\n', np.matmul(array1,array2))

soma:
 [[2 3]
 [5 6]]
subtração:
 [[ 0 -1]
 [-1 -2]]
multiplicação:
 [[1 2]
 [6 8]]
divisão:
 [[1.         0.5       ]
 [0.66666667 0.5       ]]
exponencial:
 [[ 1  1]
 [ 8 16]]
multiplicação entre matrizes:
 [[ 4  6]
 [ 8 12]]


In [8]:
# operações com arrays 

array = np.array([[1, 2, 3], [4, 5, 6], [7 , 8 ,9]])

print("soma:", array.sum())
print("multiplicação:", array.prod())
print("maior valor:", array.max(), ' index:', array.argmax()) 
print("menor valor:", array.min(), " index:", array.argmin())    


soma: 45
multiplicação: 362880
maior valor: 9  index: 8
menor valor: 1  index: 0


In [12]:
# operações estatisicas com arrays 

array = np.array([3, 56, 78, 32, 65, 0, 9])

print(array.std())       # desvio padrão, np.std(array)
print(array.mean())      # media        , np.mean(array) 
print(array.var())       # variancia    , np.var(array)
print(np.median(array))  # meio
print(np.average(array, weights = [1, 2, 3, 4, 5, 6, 7])) # media avançada

29.576604101960076
34.714285714285715
874.7755102040816
32.0
30.892857142857142


In [17]:
# axis - especifica uma dimensão do array

array = np.array([[1, 2, 3], [4, 5, 6], [7 , 8 ,9]])

print(array.sum(axis=0)) # soma das colunas
print(array.sum(axis=1)) # soma das linhas
print(array.sum(axis=0).sum()) # soma da soma das colunas, equivalente a array.sum()

[12 15 18]
[ 6 15 24]
45
