In [2]:
import numpy as np

In [ ]:
# np.arange(start, end, step)

array = np.arange(0, 10, 1)
print(array)

In [ ]:
# np.linspace(start, end, num=n) - cria um array com n(default 50) elementos entre start e end distruibuidos em "steps" iguais 

array = np.linspace(0, 10)
print(array)

In [9]:
# np.zeros() e np.ones() - cria matrizes somente com 0 ou 1

zeros = np.zeros((2, 2))
one = np.ones(4)
print(zeros)
print(one)

[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1.]


In [11]:
# np.zeros_like() e np.ones_like() - converte uma matriz em 0 ou 1

matriz = np.array([[1, 2, 3], 
                   [4, 5, 6]])
matriz_0 = np.zeros_like(matriz)
print(matriz_0)

[[0 0 0]
 [0 0 0]]


In [9]:
# transposta - não funciona com matrizes de uma dimensão

matriz = np.array([[1,2,3], [9, 2, -1]])

print(matriz.T, '\n')
print(np.transpose(matriz))

[[ 1  9]
 [ 2  2]
 [ 3 -1]] 

[[ 1  9]
 [ 2  2]
 [ 3 -1]]


In [17]:
a = np.array([1,5])
b = np.array([[2,2], [3,4]])
print(b/a)

[[2.  0.4]
 [3.  0.8]]
